/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractMyDslCompletionContributor extends TerminalsCompletionContributor {
	public AbstractMyDslCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
